version: '3'

services:
    nginx:
        image: nginx:1.21.6
        container_name: nginx 
        ports:
            - "5555:80"
        volumes:
            - ./nginx_reverse_proxy.conf:/etc/nginx/conf.d/default.conf:ro
            - ./store/static/files:/static:ro
        links:
            - node_1
            - "bbox"

    graphite:
        image: graphiteapp/graphite-statsd:1.1.8-8
        container_name: graphite
        volumes:
            - ./statsd.config.js:/opt/statsd/config.js
            - ./graphite.storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
        ports:
            - "8090:80"
            - "8125:8125/udp"
            - "8126:8126"

    grafana:
        build:
            context: ./grafana
        container_name: grafana
        ports:
            - "3000:3000"
        volumes:
            - "grafana_config:/var/lib/grafana"

    cadvisor:
        image: gcr.io/cadvisor/cadvisor:v0.44.0
        container_name: cadvisor
        links:
            - graphite
        command: -storage_driver="statsd" -storage_driver_host="graphite:8125" -storage_driver_db="cadvisor" -storage_driver_buffer_duration="1s"
        ports:
            - "8080:8080"
        volumes:
            - "/:/rootfs:ro"
            - "/var/run:/var/run:rw"
            - "/sys:/sys:ro"
            - "/var/lib/docker/:/var/lib/docker:ro"

    bbox:
        image: "arqsoft/bbox:202201.1"
        container_name: bbox
        volumes:
            - ./bbox/config.properties:/opt/bbox/config.properties
        ports:
            - "9090:9090"
            - "9091:9091"

    node_1:
        image: "node:18-alpine"
        container_name: node_1
        user: "node"
        working_dir: /home/node/app
        environment:
            - NODE_ENV=production
        volumes:
            - ./app:/home/node/app
        ports:
            - "3003:3003"
        command: sh -c 'npm install && npm ci && npm install nodemon && npm start'
        links:
            - "bbox"
            - "graphite"
            - "cadvisor"



volumes:
    grafana_config:
        driver: local
